### ISSUE TITLE
Create an updated "Understanding Application transformation scenario" video

### ISSUE THREAD

**Issue by barecode** [IBM/appnav#6]
The current "Understanding Application transformation scenario" video is based on the App Nav tech preview from early 2019. The video needs to be re-created with updated screen captures based on IBM Application Navigator 2.0, and the link on README.md "Understanding Application transformation scenario" needs to be updated to reference the new video.

**Comment by cvignola** [comment]
Latest video is based on Application Navigator running on Openshift.
